# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Node.js CI

on:
  pull_request:
    branches:
      - main # when PR merge to main
    paths:
      - "packages/contracts/contracts/**"
      - "packages/contracts/test/**"

jobs:
  ci-contract:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.17.0]

    steps:
      - name: check out git repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn v3.5.0·
        run: |
          npm i -g corepack && corepack prepare yarn@stable --activate && yarn plugin import workspace-tools
          yarn set version 3.5.0

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn

      - name: Compile contract packages
        run: cd packages/contracts; yarn build; cd -;

      - name: Run all unit tests
        run: cd packages/contracts && yarn test
